language: python
sudo: false
python:
- 2.7.10
- 2.7.13

addons:
  apt:
    packages:
    # Install binary package for lxml to speed up build
    - python-lxml
  sonarqube:
    organization: z4y4ts-github
    token:
      secure: L4Us1c2s1L9ep8sBpPL97CsrqNja4bksAXEJWmpWVLXG9dvP9P9+kVTFe3sQcyS9m/FWOGyK4PtEmk94vxDnDw1EefvY2owyCPDGcX2CWft9CzQMR64Gij03qfCx3t+h5qkzIs26HgXMgGDvzS+pspP9sY79ihFbcvQRmFXVE5nCR2QQbpeh81bgEArYELVwwiUUeUM6QcTbIMFMjFvTYRu57Sej884JnYfKOb9WGHXo2As1ky2708mNs/KnHwbQWeDo2hqTuvbj/R1+ekPlJGUBNnTqHlh0iyxqysdWxpBKjzCuqbKQsMgURWttHIjnxW12TAnFiNijFeTlCxew0ERNaZqSMOCzfA5WMDNwZ8trJRPs6sWNPBrTIjo0ReEKwXG2leqs3b4ERJVjttakfKArkGz2qFESia9css/n578KT7UISjDkKTpuVMGSET2thObzGOLtxvnx/AJl7NPls/UrJvG0C9rUxAyJix0DE434hTG+HEsMshTmunZPj0upF0hymX0fFbo7TspHhfZa07yteuZ+/L97Ck/MAz0221QVClzkZu75eTgi0eRAbCsRlgQrWaYKFvT1lYm7RCihFTscQVDrbJyAzo6AYxFBDUikCBb6HqMqAY/0LATIE+VrT1EPgsLphD/3721k9+UxUOcis34iovCbDfTBAKnFOqs=

jdk:
- oraclejdk8

cache:
  pip: true
  directories:
  - node_modules  # NPM packages

before_install:
# Install latest stable NodeJS version. Required for eslint.
- nvm install stable

install:
- make dev-install

before_script:
# Install bower, eslint, eslint-config-edx-es5 and their dependencies
- make tools
- make deps-test

script:
- make quality-py
- make quality-js
- make test
- sonar-scanner

after_success:
- make coverage
